### PR TITLE
Fixes for a few minor issues in the CMake

### PR DESCRIPTION
**Pull request by shiva**
When building using cmake on linux (out of source build directory), I get the following error:

```
CMake Error at CMakeLists.txt:113 (check_include_file):
  Unknown CMake command "check_include_file".

```

After fixing the above, I get:

```
CMake Error at CMakeLists.txt:124 (check_function_exists):
  Unknown CMake command "check_function_exists".
```

And then, I get:

```
CMake Error at src/CMakeLists.txt:361 (set_target_properties):
  set_target_properties called with incorrect number of arguments.

```

The last error, is due to the fact that we don't set NN_PACKAGE_VERSION variable for cmake to use. I solved this by moving the logic in package_version.sh into cmake directly.

After the following commits, I am able to build and run tests using the make targets (100% pass)

### CODE REVIEW

**Comment by JackDunaway** [comment]
It looks like you make have stumbled upon an issue between `check_include_file` and `check_include_files` (notices "s" on the end of one), but I'm not sure about the `NN_PACKAGE_VERSION` bit.

Can you verify that prior to building with CMake, you've removed all of the autotools source, and especially any build artifacts from previous invocations of autotools? The only place that `NN_PACKAGE_VERSION` is referenced is within the autotools script itself (https://github.com/nanomsg/nanomsg/search?q=NN_PACKAGE_VERSION&type=Code), meaning the issues you see could be due to stale build artifacts either in your repo or out-of-source build dir. (this has bitten me enough times to have the keystrokes `git clean -xfdn` memorized!)

**Comment by JackDunaway** [comment]
I think the main problem uncovered here is the include file: https://github.com/JackDunaway/featherweight-nanomsg/blob/ftw-kernel/CMakeLists.txt#L26

Note, it's plural, not singular. Compared with the invocations of the function later, which are singular, not plural.

The reason this has been flying under my radar with successful builds I believe is because this library is built as part of a bigger amalgamation, which _does_ have the correct `include()` upstream of this particular library.

Good catch!

**Comment by JackDunaway** [comment]
Beginning of one such successful build: https://travis-ci.org/featherweight/ftw-kernel/jobs/118998992#L770

**Comment by shiva** [comment]
@JackDunaway You are correct. 
1. one with the check_include_files vs check_include_file. Would you prefer to fix the "include" instead?(https://github.com/JackDunaway/featherweight-nanomsg/pull/1/commits/289fa60ea7075c601fc768fd952853ce3bcf4a93)
2. no include for check_function_exists (https://github.com/JackDunaway/featherweight-nanomsg/pull/1/commits/b75b03ff64030fa922e49d904a7f0ad1e3a0f6c4). This is required to get by the next issue
3. It is used here
   https://github.com/JackDunaway/featherweight-nanomsg/blob/ftw-kernel/src/CMakeLists.txt#L362.
   The value of NN_PACKAGE_VERSION is used to set the build version of the library. If the variable is unset, we will see the error as shown in my original post. The fix I made in this commit (https://github.com/JackDunaway/featherweight-nanomsg/pull/1/commits/ad6b73ef8d6451e6f23b01a04af7498bd9e58cdf), essentially calculates the build version as per the script package_version.sh in cmake itself and sets the variable as expected
   This removes the need to run something in the shell and obviates the need for the script once all platforms are supported via cmake.

**Comment by shiva** [comment]
Checked without my last commit + git clean. Issue w.r.t NN_PACKAGE_VERSION persist. I.e we still need https://github.com/JackDunaway/featherweight-nanomsg/pull/1/commits/ad6b73ef8d6451e6f23b01a04af7498bd9e58cdf

```
[{} cmakeify-nanomsg]$git clean -xfd 
Removing build/
[{} cmakeify-nanomsg]$mkdir build && cd build && cmake ..
-- The C compiler identification is GNU 4.4.7
....  (truncated for brevity)
....
-- Performing Test NN_HAVE_MSG_CONTROL - Success
CMake Error at src/CMakeLists.txt:361 (set_target_properties):
  set_target_properties called with incorrect number of arguments.

-- Autobahn TestSuite for WebSocket is disabled.
-- Configuring incomplete, errors occurred!
See also "/workspace/git/eshivel/nanomsg.git/cmakeify-nanomsg/build/CMakeFiles/CMakeOutput.log".
See also "/workspace/git/eshivel/nanomsg.git/cmakeify-nanomsg/build/CMakeFiles/CMakeError.log".
[{} build]$

```

**Comment by JackDunaway** [comment]
> The value of NN_PACKAGE_VERSION is used to set the build version of the library. If the variable is unset, we will see the error as shown in my original post

You're right. I've been building libnanomsg as a static lib, where obvious problems like this didn't flush out.

Thank you for the work on a tricky bit like this! Will definitely pull this commit (it's late evening my time; will dive in tomorrow)

**Comment by shiva** [comment]
Sure thing! Thanks for spending time understanding my changes.

**Pull request merged**
